name: Build and test

on:
- workflow_dispatch

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  Windows:
    strategy:
      fail-fast: true
      matrix:
        image:
        - "2022"

    uses: ./.github/workflows/windows.yml
    with:
      image: ${{ matrix.image }}

  Windows-Installer:
    name: Windows Installer
    strategy:
      fail-fast: true
      matrix:
        image:
        - "2022"

    uses: ./.github/workflows/windows.yml
    with:
      image: ${{ matrix.image }}
      package: true
      artifact-suffix: "-installer"
