name: Release

on:
- workflow_dispatch

jobs:
  MacOS:
    strategy:
      fail-fast: true
      matrix:
        args:
          - image: macos-15
    uses: ./.github/workflows/macos.yml
    with:
      image: ${{ matrix.args.image }}
      build-type: Release
